from enum import Enum


class FahrzeugKategorie(str, Enum):
    DOPPELSTOCKSTEUERWAGENERSTEZWEITEKLASSE = "DOPPELSTOCKSTEUERWAGENERSTEZWEITEKLASSE"
    DOPPELSTOCKSTEUERWAGENZWEITEKLASSE = "DOPPELSTOCKSTEUERWAGENZWEITEKLASSE"
    DOPPELSTOCKWAGENERSTEKLASSE = "DOPPELSTOCKWAGENERSTEKLASSE"
    DOPPELSTOCKWAGENERSTEZWEITEKLASSE = "DOPPELSTOCKWAGENERSTEZWEITEKLASSE"
    DOPPELSTOCKWAGENZWEITEKLASSE = "DOPPELSTOCKWAGENZWEITEKLASSE"
    HALBSPEISEWAGENERSTEKLASSE = "HALBSPEISEWAGENERSTEKLASSE"
    HALBSPEISEWAGENZWEITEKLASSE = "HALBSPEISEWAGENZWEITEKLASSE"
    LOK = "LOK"
    REISEZUGWAGENERSTEKLASSE = "REISEZUGWAGENERSTEKLASSE"
    REISEZUGWAGENERSTEZWEITEKLASSE = "REISEZUGWAGENERSTEZWEITEKLASSE"
    REISEZUGWAGENZWEITEKLASSE = "REISEZUGWAGENZWEITEKLASSE"
    SPEISEWAGEN = "SPEISEWAGEN"
    STEUERWAGENERSTEKLASSE = "STEUERWAGENERSTEKLASSE"
    STEUERWAGENERSTEZWEITEKLASSE = "STEUERWAGENERSTEZWEITEKLASSE"
    STEUERWAGENZWEITEKLASSE = "STEUERWAGENZWEITEKLASSE"
    TRIEBKOPF = "TRIEBKOPF"
    VALUE_16 = ""

    def __str__(self) -> str:
        return str(self.value)
